Repository DataIntellectTech/TorQ, pull requests merged in 2018-10, with the labels that each got.

#121 Improve .proc.init functionality
  torq.q
Labels: bug, enhancement

#122 Remove logging for 0D keepquerytime
  code/processes/gateway.q
Labels: bug, enhancement

#123 Add qcon alias in torq.sh script
  setenv.sh
  torq.sh
Labels: enhancement

#126 Fix default .z.pi to allow qcon
  torq.q
Labels: bug

#128 Gateway Null Hang
  code/processes/gateway.q
Labels: bug

#127 Export config
  code/common/api.q
  code/common/apidetails.q
  docs/utilities.md
Labels: enhancement

#124 Grafana for TorQ
  code/common/grafana.q
  config/settings/default.q
  docs/graphics/GrafanDropDown.png
  docs/utilities.md
Labels: enhancement, newfeature

#129 edit debug arg check to allow extra flags
  torq.sh
Labels: bug

#130 WDB reloadend function call
  code/processes/wdb.q
Labels: enhancement
