Repository DataIntellectTech/TorQ, pull requests merged in 2019-11, with the labels that each got.

#166 Fix for windows housekeeping inconsistency
  code/processes/housekeeping.q
  config/settings/housekeeping.q
Labels: bug

#170 enlist dtsuffix
  code/processes/reporter.q
Labels: bug

#175 Store TP logs and HDB in separate location
  setenv.sh
Labels: enhancement

#173 Add dqe process to TorQ
  code/processes/dqe.q
  tests/dqetests.csv
Labels: newfeature
