Repository DataIntellectTech/TorQ, pull requests merged in 2020-07, with the labels that each got.

#302 Add top function to torq.sh
  code/profiler/top.q
  setenv.sh
  torq.sh
Labels: enhancement

#303 Code Profiler Documentation
  code/profiler/top.q
  docs/gettingstarted.md
Labels: documentation

#306 Fix docs format in Code Profiler section
  docs/gettingstarted.md
Labels: documentation

#307 Update chained tickperplant startup
  code/handlers/trackservers.q
  code/processes/chainedtp.q
  config/settings/chainedtp.q
Labels: bug

#309 Rdb log replaying, timezone configuration
  code/common/eodtime.q
  code/common/subscriptions.q
  code/processes/rdb.q
  code/processes/segmentedtickerplant.q
  code/segmentedtickerplant/pubsub.q
  code/segmentedtickerplant/stplog.q
  code/segmentedtickerplant/stpmeta.q
  docs/Processes.md
  tests/rdb/replaylog.csv
  tests/stp/customlogs.csv
  tests/stp/custommeta.csv
  tests/stp/customperiodroll.csv
  tests/stp/dayroll.csv
  tests/stp/meta.csv
  tests/stp/periodroll.csv
  tests/stp/subfilt.csv
  tests/stp/subold.csv
  tests/stp/tablelogs.csv
Labels: enhancement
