Repository DataIntellectTech/TorQ, pull requests merged in 2020-01, with the labels that each got.

#197 DQE check rerun functionality
  code/processes/dqe.q
Labels: enhancement

#203 Nullcheck
  code/processes/dqe.q
Labels: enhancement

#204 Gw documentation improvement
  code/handlers/permissions.q
  code/processes/gateway.q
  docs/Processes.md
Labels: documentation

#208 Log message fixes for check monitor code, make it default to not save to disk
  code/monitor/checkmonitor.q
  code/processes/monitor.q
  config/settings/monitor.q
Labels: bug

#189 Remove double running of unit tests
  tests/k4unit.q
Labels: bug

#193 Datadog Integration
  code/common/datadog.q
  code/monitor/datadogchecks.q
  code/processes/tickerplant.q
  config/settings/default.q
  datadog/Example_TorQ_Monitoring_Dashboard.json
  datadog/monitors/monitors.zip
  datadog/setupdatadog.sh
  docs/graphics/datadog1.png
  docs/graphics/datadog2.png
  docs/monit.md
  setenv.sh
Labels: newfeature

#202 Schema checker for DQE
  code/dqe/schemacheck.q
  config/dqeconfig.csv
Labels: newfeature

#206 DQE anomalycheck
  code/processes/dqe.q
Labels: enhancement

#198 Add function to dqe that runs comparisons between two or more processes
  code/dqe/chkslowsub.q
  code/dqe/constructcheck.q
  code/dqe/tablecount.q
  code/processes/dqe.q
  config/dqeconfig.csv
  tests/dqe/failchk.csv
Labels: enhancement

#205 Crossed Market Alert
  code/dqe/xmarketalert.q
  config/dqeconfig.csv
Labels: enhancement

#207 Gw imprv
  code/gateway/gatewaylib.q
  code/processes/gateway.q
  config/settings/gateway.q
  docs/Processes.md
  tests/gwtests.csv
Labels: documentation, enhancement

#214 Sym file checker
  code/dqe/symfilecheck.q
  config/dqeconfig.csv
  config/settings/dqe.q
Labels: enhancement

#216 DQE d file check
  code/processes/dqe.q
Labels: enhancement

#210 Allow current checks of DQE to run in a HDB
  code/common/dqe.q
  code/dqe/constructcheck.q
  code/dqe/freeform.q
  code/processes/dqe.q
  config/dqeconfig.csv
Labels: enhancement
